name: Validate library's code quality.

on:
    push:
        branches:
            - main
            - development

    pull_request:
        branches:
            - main
            - development

defaults:
    run:
        shell: bash

jobs:
    validate-bun:
        name: Validate with Bun.
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository.
              uses: actions/checkout@v6

            - name: Setup Bun.
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies.
              run: bun install

            - name: Validate code using ESlint.
              run: bun run lint

            - name: Validate code using TypeScript Compiler.
              run: bunx tsc --noEmit

    validate-node:
        name: Validate with Bun.
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository.
              uses: actions/checkout@v6

            - name: Setup Node.js.
              uses: actions/setup-node@v6.1.0
              with:
                  node-version: latest

            - name: Install dependencies.
              run: npm install

            - name: Validate code using ESlint.
              run: npm run lint

            - name: Validate code using TypeScript Compiler.
              run: npx tsc --noEmit
